### ISSUE TITLE
Transaction too Large error

### ISSUE THREAD

**Issue by alexvenom** [AvianNetwork/Avian#53] opened 2022-01-18 17:45 UTC
Trying to send some AVN from local wallet to Exchange. Set the correct value and fees, but a "Transaction too large" error shows, followed by an "Transaction Creation failed".
No descriptions or whatsoever to help finish the transaction.

**Comment by taperj** [comment] 2022-01-18 18:02
This occurs when you have too many inputs selected. You'll need to go to "coin control" and send a few transactions to yourself to consolidate inputs, once below the max transaction size it will work. Generally happens when many small mining transactions(or other) stack up in the wallet. It's not a bug, standard behavior.

**Comment by alamshafil** [comment] 2022-02-23 22:41
We can add additional info when this error occurs. Maybe tell the user to consolidate their inputs?

**Comment by alamshafil** [comment] 2022-02-23 23:46
Closing for now, will be reopened if needed.

**Closed by alamshafil** 2022-02-23 23:46 UTC
Labels: not-issue
