### ISSUE TITLE
remove stdout spamming

### ISSUE THREAD

**Issue by fdoving** [AvianNetwork/Avian#34] opened 2021-12-14 23:30 UTC
Did not investigate where it comes from.
Looks like some debug-info someone forgot to disable.

Lots of this:

![image](https://user-images.githubusercontent.com/26197922/146095684-2156af94-37f5-4219-8fb1-65ed27716068.png)

**Comment by Xangis** [comment] 2021-12-15 01:24
I tried to find this in the code at one point by grepping for "##" and couldn't -- it's going to be formatted output that might be tricky to track down.

**Comment by fdoving** [comment] 2021-12-15 07:23
Looks like this line: 
https://github.com/AvianNetwork/Avian/blob/790a0d8de43272439b6524845bb3a2d0681e14e5/src/script/interpreter.cpp#L249

**Comment by alamshafil** [comment] 2021-12-15 18:32
This has been bothering me forever; I never took the time to find the root cause. I appreciate you fixing this! Merged #36

**Closed by alamshafil** 2021-12-15 18:32 UTC
